### ISSUE TITLE
Laravel Auditing

### ISSUE THREAD

**Issue by leduardoa** [luissobrinho/builder#10]
This package will help you understand changes in your Eloquent models, by providing information about possible discrepancies and anomalies that could indicate business concerns or suspect activities.

Laravel Auditing allows you to keep a history of model changes by simply using a trait. Retrieving the audited data is straightforward, making it possible to display it in various ways.

**Comment by luissobrinho** [comment]
Developing

**Comment by luissobrinho** [comment]
Implementation finalized, follow link with details [https://github.com/luissobrinho/builder/tree/v0.0.10#auditing](https://github.com/luissobrinho/builder/tree/v0.0.10#auditing)
