### ISSUE TITLE
Debug Bar

### ISSUE THREAD

**Issue by leduardoa** [luissobrinho/builder#8]
To implement https://github.com/barryvdh/laravel-debugbar
With activation only on permission see debug

**Comment by luissobrinho** [comment]
Implementing

**Comment by luissobrinho** [comment]
Implementation of Debugbar,
Follows documentation: [https://github.com/luissobrinho/builder/releases/tag/v0.0.11](https://github.com/luissobrinho/builder/releases/tag/v0.0.11)
